# Generated by Django 4.2.3 on 2023-07-18 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Login",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.EmailField(max_length=254, unique=True)),
                ("usertype", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="State",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("state_name", models.CharField(max_length=200)),
                ("address", models.TextField(max_length=300)),
                ("contact_number", models.BigIntegerField()),
                ("login_id", models.IntegerField()),
            ],
        ),
    ]
