# Generated by Django 4.2.3 on 2023-07-24 07:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Login",
        ),
        migrations.RemoveField(
            model_name="state",
            name="address",
        ),
        migrations.RemoveField(
            model_name="state",
            name="contact_number",
        ),
        migrations.RemoveField(
            model_name="state",
            name="login_id",
        ),
        migrations.RemoveField(
            model_name="state",
            name="state_name",
        ),
        migrations.AddField(
            model_name="state",
            name="host",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="state",
            name="latitiude",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="state",
            name="location",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="state",
            name="longitude",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="state",
            name="phone",
            field=models.BigIntegerField(null=True),
        ),
    ]
