# Generated by Django 4.2.3 on 2023-07-24 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0003_state_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="state",
            name="state",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
