# Generated by Django 4.2.3 on 2023-07-24 13:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("base", "0005_volunteer"),
    ]

    operations = [
        migrations.CreateModel(
            name="EndUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, null=True)),
                ("phone", models.BigIntegerField(null=True)),
                ("state", models.CharField(max_length=200, null=True)),
                ("location", models.TextField(null=True)),
                ("latitude", models.TextField(null=True)),
                ("longitude", models.TextField(null=True)),
                (
                    "host",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
