# Generated by Django 4.2.3 on 2023-07-25 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0007_alert"),
    ]

    operations = [
        migrations.CreateModel(
            name="Needs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("requirements", models.TextField(null=True)),
                ("status", models.IntegerField(default=0)),
                (
                    "host",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="base.volunteer",
                    ),
                ),
            ],
        ),
    ]
