# Generated by Django 4.2.3 on 2023-07-25 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0008_needs"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alert",
            name="status",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="enduser",
            name="state",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="base.state"
            ),
        ),
        migrations.AlterField(
            model_name="volunteer",
            name="state",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="base.state"
            ),
        ),
    ]
