# Generated by Django 4.2.3 on 2023-08-03 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0008_product"),
    ]

    operations = [
        migrations.CreateModel(
            name="cart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "host",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="base.enduser",
                    ),
                ),
                (
                    "products",
                    models.ManyToManyField(
                        blank=True, related_name="products", to="base.product"
                    ),
                ),
            ],
        ),
    ]
