# Generated by Django 4.2.3 on 2023-07-25 06:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("base", "0009_alter_alert_status_alter_enduser_state_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="state",
            name="host",
        ),
        migrations.RemoveField(
            model_name="state",
            name="latitiude",
        ),
        migrations.RemoveField(
            model_name="state",
            name="location",
        ),
        migrations.RemoveField(
            model_name="state",
            name="longitude",
        ),
        migrations.RemoveField(
            model_name="state",
            name="phone",
        ),
        migrations.RemoveField(
            model_name="state",
            name="state",
        ),
        migrations.CreateModel(
            name="StateCommittee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, null=True)),
                ("phone", models.BigIntegerField(null=True)),
                ("location", models.TextField(null=True)),
                ("latitiude", models.TextField(null=True)),
                ("longitude", models.TextField(null=True)),
                (
                    "host",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "state",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="base.state",
                    ),
                ),
            ],
        ),
    ]
