# Generated by Django 4.2.3 on 2023-07-26 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0010_remove_state_host_remove_state_latitiude_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="needs",
            name="is_verified_by_admin",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="needs",
            name="is_verified_by_state",
            field=models.IntegerField(default=0),
        ),
    ]
