# Generated by Django 4.2.3 on 2023-07-27 13:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0011_needs_is_verified_by_admin_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="needs",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="needs",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
