# Generated by Django 4.2.3 on 2023-08-04 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0012_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="active",
            field=models.IntegerField(default=0),
        ),
    ]
